# Generated by Django 2.2.3 on 2019-07-16 00:11

import Portfolio.checker
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('accountid', models.IntegerField(default=0)),
                ('date_opened', models.CharField(max_length=255)),
                ('external_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('user', 'date', 'accountid', 'date_opened', 'external_name'),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', Portfolio.checker.ContentTypeRestrictedFileField(upload_to='uploads/')),
                ('status', models.CharField(max_length=255)),
                ('file_stored', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=255)),
                ('data', models.ManyToManyField(related_name='data', to='Portfolio.Stuff')),
            ],
        ),
    ]
