# Generated by Django 2.2.3 on 2019-07-16 00:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='others',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=True),
            preserve_default=False,
        ),
    ]
