# Generated by Django 2.2.3 on 2019-07-14 18:26

import Portfolio.checker
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20190714_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='file',
            field=Portfolio.checker.ContentTypeRestrictedFileField(default=datetime.datetime(2019, 7, 14, 18, 26, 3, 922736, tzinfo=utc), upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
