# Generated by Django 2.2.3 on 2019-07-16 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_stuff_others'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuff',
            options={'ordering': ('filename', 'user', 'date', 'accountid', 'date_opened', 'external_name', 'others')},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='filename',
        ),
        migrations.AddField(
            model_name='stuff',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
