# Generated by Django 2.2.3 on 2019-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20190716_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
