# Generated by Django 2.2.3 on 2019-07-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_portfolio_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('title',)},
        ),
    ]
