# Generated by Django 2.2.3 on 2019-07-17 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_auto_20190717_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuff',
            options={'ordering': ('status', 'filename', 'user', 'date', 'accountid', 'date_opened', 'external_name', 'others')},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='status',
        ),
        migrations.AddField(
            model_name='stuff',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
